@url = /products
@uri = {{hostname}}{{version}}{{url}}

### GET ALL
# @name products
GET {{uri}} HTTP/1.1
Content-Type: application/json

### CREATE
POST {{uri}} HTTP/1.1
Content-Type: application/json

{
  "name": "productName",
  "category": "productCategory",
  "price": 12000,
  "imgURL": "productPath"
}

### GET BY ID
GET {{uri}}/{{products.response.body.$[0]._id}} HTTP/1.1
Content-Type: application/json

### UPDATE BY ID
PUT {{uri}}/{{products.response.body.$[0]._id}} HTTP/1.1
Content-Type: application/json


{
  "name": "productName",
  "category": "productCategory",
  "price": 12000,
  "imgURL": "productPath"
}

### DELETE BY ID
DELETE {{uri}}/{{products.response.body.$[0]._id}} HTTP/1.1
Content-Type: application/json
